### ISSUE TITLE
what is the difference between source and target

### ISSUE THREAD

**Issue by Jiaxin-lucky** [shiyegao/DDA#10]
thanks for your beautiful work, I wonder the difference between source and target. specifically, in the paper, the diagram shows that the source and target are the same picture with different corruption, is this right in your code? I mean the sources are the groundtruth for targets. hope for your answering.

**Comment by shiyegao** [comment]
Thank you for your appreciation. Allow me to clarify some important concepts related to our project:

- **Source**: The source refers to the natural, uncorrupted images, often considered the ground truth in our context.
- **Target**: The target images are the ones that have been corrupted or altered in some way.
- **Objective**: Our primary goal is to employ a diffusion model to adapt the target images back to the source domain. Importantly, we achieve this **without relying on any source images** during the adaptation process. The diffusion model itself is trained using the source images.

Regarding the code structure:

- ``image_adapt``: This section of our code directly aligns with our primary objective, where we work on adapting the target images to the source domain.

- ``model_adapt``: On the other hand, the ``model_adapt`` portion is dedicated to evaluation purposes. It's essential to note that our ensemble mechanism combines only the target image with our adapted one. Importantly, it operates **independently of any source images**.

If you have any questions or need clarification about our code, please don't hesitate to provide relevant links to specific code lines. We are more than happy to assist you further.
