### ISSUE TITLE
Ensemble approach

### ISSUE THREAD

**Issue by dineshdaultani** [shiyegao/DDA#11]
Hi Authors, 
Thanks for providing the source code. I have a question as follows:
In the paper it's mentioned that average confidence of test input and adapted input for the self-ensemble. However, in the source code `model_adapt/evaluation.py`, there are several possibilities of `confidence` such as `confidence, confidence_sum, and confidence_fuse`, so which ensemble method specifically is the proposed one?
Additionally, the default ensemble approach in `test.sh` is `sum` method. 

Could you please let me know soon. Thanks!

**Comment by shiyegao** [comment]
In the paper appendix, we have provided a detailed comparison.
- link: https://arxiv.org/pdf/2207.03442.pdf

In our experiment, we take the 'sum' method.

**Comment by dineshdaultani** [comment]
Thanks for the quick response. I understand the `sum` method is your proposal. I checked the appendix that you provided in CVPR, but this arxiv version appendix is different than the CVPR version. Thanks for providing the arxiv pdf. 

I have another query as follows:
- Should I select option `--ensemble second` if I would like to just use generated diffusion images for the prediction or any other mode?

**Comment by shiyegao** [comment]
Yes, the 'second' option is to predict the generated diffusion images.

The detailed 'first' and 'second' option corresponds to the [config](https://github.com/shiyegao/DDA/blob/main/model_adapt/configs/_base_/datasets/imagenetc_ReCr2.py#L11C14-L11C15).

**Comment by dineshdaultani** [comment]
Got it. Thanks for the quick clarifications. Really appreciate it.
