### ISSUE TITLE
Inference on muliple GPUs

### ISSUE THREAD

**Issue by KIRAN-MK-211** [shiyegao/DDA#14]
Hello authors! Excellent work on Adaptation of Diffusion Models. I wanted to know how to do inference on multiple GPUs. Thanks in advance!

**Comment by shiyegao** [comment]
Thanks for your appreciation!

We suggest using data parallelism. By dividing your dataset into different splits, you can perform multiple inference tasks independently on different GPUs.

**Comment by KIRAN-MK-211** [comment]
Would you suggest any library in particular please?

**Comment by shiyegao** [comment]
You can do inference on multiple GPUs in this way: https://github.com/shiyegao/DDA/blob/main/image_adapt.sh#L5

**Comment by KIRAN-MK-211** [comment]
Thanks a lot!
