### ISSUE TITLE
Can DDA perform well in other tasks as well?

### ISSUE THREAD

**Issue by zh994** [shiyegao/DDA#15]
Hello, I would like to ask if the DDA you proposed can get good results in other tasks as well? Like segmentation?

**Comment by shiyegao** [comment]
I believe that DDA can also perform well in other tasks, such as segmentation.

While we haven't made such attempts yet, there's strong evidence to support this view. In our paper, "Figure 5. Visualization of updates for ablations of diffusion" demonstrates that corrupted images undergo significant adaptation in the pixel space. Additionally, the diffusion model infuses substantial information to purify the corrupted images in the latent space.

If you are interested in exploring this direction, we would be happy to provide assistance.
