### ISSUE TITLE
Multi GPU training

### ISSUE THREAD

**Issue by ghost** [shiyegao/DDA#4]
Hi, I was wondering how could you activate multiple gpu training in parallel.

I have done CUDA_VISIBLE_DEVICES = 0,1 

But it still does not work.

**Comment by shiyegao** [comment]
Do you mean sampling by Diffusion? In this repo, we do not need the TRAINING part.

**Comment by jla465** [comment]
Yes, I meant sampling. How can we do it in parallel?
Thank you.
