### ISSUE TITLE
How to add the original image as a condition to the network？

### ISSUE THREAD

**Issue by zenghy96** [shiyegao/DDA#5]
The `model_kwargs['ref_img']` is assigned the original image, and is finally inputted into the UNetModel (the `ref_img` in image_adapt/guided_diffusion/unet.py, line 634, def forward(self, x, timesteps, y=None, ref_img=None)).  
It seems that the `ref_img` is not embedded and used in the forward function.

**Comment by Jialing-Zhang** [comment]
Yes, the ref_img is not embedded and utilized in the forward function. We did not use the original image as a condition for the network. Instead, the condition is incorporated through gradient information.
