### ISSUE TITLE
Some issues with other domains

### ISSUE THREAD

**Issue by cctsai831** [shiyegao/DDA#7]
I can't run the code for my experiment.
The setting of my experiment is as follows:
Source domain: MNIST
Target domain: USPS

The problem I encounter is that line 87 of `image_sample.py` cannot work successfully and then the whole program is stuck.

Thanks!f

**Comment by shiyegao** [comment]
It seems that there is room for improvement in the data loader for your dataset. I suggest following the reported error and designing a suitable data loading and processing pipeline to address the issue.
