### ISSUE TITLE
DDA on other datasets

### ISSUE THREAD

**Issue by wangyunnan** [shiyegao/DDA#8]
How can I use DDA on other datasets? It seems that you are not training a diffusion model, but simply taking the pre-training weights.

**Comment by shiyegao** [comment]
Yes, our work builds upon the Guided-Diffusion weights from the pre-trained diffusion model. Regarding the utilization of DDA on other datasets, we have three suggestions:

1. Pre-train a diffusion model on your source dataset. Please note that this process may require substantial computational resources.
2. Explore open-source pretrained diffusion models that have been trained on a similar source domain as your specific problem.
3. Additionally, for applications, you may also consider utilizing some SOTA diffusion models, like the Stable Diffusion weights, which can be found [here](https://huggingface.co/CompVis).
